import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/providers/ContextProvider";
import { cn } from "@/libs/utils";
import Navbar from "@/components/Navbar";
import CreateFormModal from "@/components/modals/CreateFormModal";
import PreviewModal from "@/components/modals/PreviewModal";
import Loading from "@/components/modals/LoadingModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "scroll-bar  h-screen w-screen  bg-black  text-white",
        )}
      >
        <ContextProvider>
          {/* modal */}
          <CreateFormModal />
          <Navbar />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
