import { cn } from "@/libs/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SubmitLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div
      className={cn(
        inter.className,
        "scroll-bar  h-screen w-screen  bg-black  text-white",
      )}
    >
      {children}
    </div>
  );
};

export default SubmitLayout;
